# Generated by Django 3.0.3 on 2021-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_number', models.CharField(max_length=254)),
                ('customer_name', models.CharField(max_length=254)),
                ('origin', models.CharField(max_length=254)),
                ('destination', models.CharField(max_length=254)),
                ('booking_date', models.CharField(max_length=254)),
                ('number_of_boxes', models.IntegerField()),
            ],
        ),
    ]
